### ISSUE TITLE
problem to install

### ISSUE THREAD

**Issue by hugemosu** [akarki58/Rocker_app_linux#1]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f543f3a39d8>, 'rocker_app_v3.model_rocker_report')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 650, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 741, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 747, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_model.py", line 1397, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_model.py", line 1386, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: rocker_app_v3.model_rocker_report

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 650, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 741, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 747, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_model.py", line 1397, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_model.py", line 1386, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: rocker_app_v3.model_rocker_report" while parsing /opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/rocker_app_v3/security/rocker_security.xml:29, near
<record id="rocker_report_user_rule" model="ir.rule">
      <field name="name">Rocker Reports record rule for users</field>
      <field name="model_id" ref="model_rocker_report"/>
      <field name="groups" eval="[(4, ref('rocker_app_v3.rocker_group_user'))]"/>
      <field name="domain_force">['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]</field>
    </record>

**Comment by akarki58** [comment]
Has somerhing to do with accesss rights

Check that user has a company information and check also report security settings (selected company can execute report).

This: company_id','child_of',[user.company_id.id])]. Check if user belongs to to the parent company...I have not tested this parent child company thing a lot

Antti

Hanki Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: hugemosu ***@***.***>
Sent: Thursday, June 24, 2021 12:31:22 AM
To: akarki58/Rocker_app_2021 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [akarki58/Rocker_app_2021] problem to install (#1)


Error:
Odoo Server Error

Traceback (most recent call last):
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/cache.py", line 88, in lookup
r = d[key]
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/func.py", line 69, in wrapper
return func(self, *args, **kwargs)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/lru.py", line 44, in getitem
a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f543f3a39d8>, 'rocker_app_v3.model_rocker_report')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 758, in parse
self._tags[rec.tag](rec, de, mode=mode)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 650, in _tag_record
f_val = self.id_get(f_ref)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 741, in id_get
res = self.model_id_get(id_str, raise_if_not_found)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 747, in model_id_get
return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_model.py", line 1397, in xmlid_to_res_model_res_id
return self.xmlid_lookup(xmlid)[1:3]
File "", line 2, in xmlid_lookup
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/cache.py", line 93, in lookup
value = d[key] = self.method(*args, **kwargs)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_model.py", line 1386, in xmlid_lookup
raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: rocker_app_v3.model_rocker_report

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 654, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 312, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/pycompat.py", line 87, in reraise
raise value
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 696, in dispatch
result = self._call_function(**self.params)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 344, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/service/model.py", line 97, in wrapper
return f(dbname, *args, **kwargs)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 337, in checked_call
result = self.endpoint(*a, **kw)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 939, in call
return self.method(*args, **kw)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/http.py", line 517, in response_wrap
response = f(*args, **kw)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/web/controllers/main.py", line 966, in call_button
action = self._call_kw(model, method, args, {})
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/web/controllers/main.py", line 954, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/api.py", line 749, in call_kw
return _call_kw_multi(method, model, args, kwargs)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/api.py", line 736, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "", line 2, in button_immediate_install
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
return method(self, *args, **kwargs)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
return self._button_immediate_function(type(self).button_install)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
modules.registry.Registry.new(self._cr.dbname, update_module=True)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/modules/registry.py", line 86, in new
odoo.modules.load_modules(registry._db, force_demo, status, update_module)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/modules/loading.py", line 421, in load_modules
loaded_modules, update_module, models_to_check)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/modules/loading.py", line 313, in load_marked_modules
perform_checks=perform_checks, models_to_check=models_to_check
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/modules/loading.py", line 222, in load_module_graph
load_data(cr, idref, mode, kind='data', package=package, report=report)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/modules/loading.py", line 68, in load_data
tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 802, in convert_file
convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 865, in convert_xml_import
obj.parse(doc.getroot(), mode=mode)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 764, in parse
exc_info[2]
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/pycompat.py", line 86, in reraise
raise value.with_traceback(tb)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 758, in parse
self._tags[rec.tag](rec, de, mode=mode)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 650, in _tag_record
f_val = self.id_get(f_ref)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 741, in id_get
res = self.model_id_get(id_str, raise_if_not_found)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/convert.py", line 747, in model_id_get
return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_model.py", line 1397, in xmlid_to_res_model_res_id
return self.xmlid_lookup(xmlid)[1:3]
File "", line 2, in xmlid_lookup
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/tools/cache.py", line 93, in lookup
value = d[key] = self.method(*args, **kwargs)
File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/base/models/ir_model.py", line 1386, in xmlid_lookup
raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: rocker_app_v3.model_rocker_report" while parsing /opt/bitnami/apps/odoo/lib/odoo-12.0.post20190518-py3.7.egg/odoo/addons/rocker_app_v3/security/rocker_security.xml:29, near

Rocker Reports record rule for users


['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]
